use std::collections::HashMap;
use std::thread;
use assembler::Assembler;
use assembler::naive_assembler::NaiveAssembler;
use crossbeam_channel::{unbounded, Receiver, Sender};
use messages::{ChatRequest, ChatResponse, Message, MessageType, MessageUtilities, RequestType, ResponseType};
use messages::node_event::NodeEvent;
use ntest::timeout;
use wg_2024::network::{NodeId, SourceRoutingHeader};
use wg_2024::packet::{Ack, FloodResponse, NodeType, Packet, PacketType};
use ap_server::{DibServer, Command, DibGetter, DibServerTrait};
use crate::common::{process_initial_flood_requests, send_message_and_receive_acks};

mod common;

#[test]
#[timeout(2000)]
fn check_communication() -> std::thread::Result<()> {
    let server_node_id = 0;

    let mut connected_drones = HashMap::new();
    let mut drones = HashMap::new();
    let (tx, rx) = unbounded();

    connected_drones.insert(1, tx);
    drones.insert(1, rx);

    let (tx, rx) = unbounded();
    connected_drones.insert(9, tx);
    drones.insert(9, rx);

    let (server_public_tx, server_public_rx) = unbounded();
    let (server_to_sc_tx, server_to_sc_rx) = unbounded();

    let (mut server, command_tx) = DibServer::new_communication_server(
        server_node_id,
        server_public_rx,
        connected_drones,
        server_to_sc_tx
    );

    let server_handler = thread::Builder::new()
        .name(format!("communication_server_{}", server.get_node_id()))
        .spawn(move || {
            server.run()
        })
        .unwrap();

    process_initial_flood_requests(&mut drones, &server_public_tx);

    let source = 9;
    let destination = server_node_id;
    let session_id = 4;

    let server_to_drone_source_rx = drones.get(&source).unwrap();

    register_node_id(source, destination, session_id, &server_public_tx, server_to_drone_source_rx);

    let session_id = 7;
    let expected_message = Message {
        source: destination,
        destination: source,
        session_id,
        content: MessageType::Response(ResponseType::ChatResponse(ChatResponse::ClientList(vec![source]))),
    };

    let expected_routing_header = SourceRoutingHeader {
        hop_index: 1,
        hops: vec![destination, source],
    };

    get_client_list(source, destination, session_id, &server_public_tx, &server_to_drone_source_rx, expected_message, expected_routing_header);

    let session_id = 87;
    let server_to_drone_source_rx = drones.get(&1).unwrap();
    register_node_id(1, destination, session_id, &server_public_tx, &server_to_drone_source_rx);

    let source = 9;
    let destination = 1;
    let session_id = 56;
    let chat_request = ChatRequest::SendMessage {
        from: source,
        to: destination,
        message: "Implements quackable".to_string(),
    };

    send_message_to(
        source,
        destination,
        server_node_id,
        drones.get(&source).unwrap(),
        &server_public_tx,
        drones.get(&destination).unwrap(),
        session_id,
        chat_request
    );

    let shutdown = Command::Quit;
    let _ = command_tx.send(shutdown);

    server_handler.join()
}

fn send_message_to(
    source: NodeId,
    destination: NodeId,
    server_node_id: NodeId,
    server_to_source_rx: &Receiver<Packet>,
    drones_to_server_tx: &Sender<Packet>,
    server_to_destination_rx: &Receiver<Packet>,
    session_id: u64,
    chat_request: ChatRequest,
) {
    let ChatRequest::SendMessage { from, to, message } = chat_request.clone() else { panic!("Unexpected chat request type {chat_request:?}"); };

    let request = Message {
        source,
        destination: server_node_id,
        session_id,
        content: MessageType::Request(RequestType::ChatRequest(chat_request.clone())),
    };

    send_message_and_receive_acks(server_to_source_rx, drones_to_server_tx, source, server_node_id, session_id, request);

    let expected_destination_message = Message {
        source: server_node_id,
        destination,
        session_id: 0, // randomly generated by server
        content: MessageType::Response(ResponseType::ChatResponse(ChatResponse::MessageFrom {
            from,
            message,
        })),
    };

    let expected_fragments = NaiveAssembler::disassemble(&expected_destination_message.stringify().into_bytes());

    let mut received_fragments = Vec::new();
    for _ in 0..expected_fragments.len() {
        let received = server_to_destination_rx.recv().unwrap();
        match received.pack_type {
            PacketType::MsgFragment(fragment) => received_fragments.push(fragment),
            _ => panic!("Received unexpected packet {received:?}"),
        }
    }
    received_fragments.sort_by_key(|fragment| fragment.fragment_index);

    let received_message = NaiveAssembler::reassemble(&received_fragments);
    let received_message = String::from_utf8(received_message).unwrap();
    let received_message: Message = MessageUtilities::from_string(received_message).unwrap();

    assert_eq!(received_message.source, expected_destination_message.source);
    assert_eq!(received_message.destination, expected_destination_message.destination);
    assert_eq!(received_message.content, expected_destination_message.content);

    let expected_source_message = Message {
        source: server_node_id,
        destination: source,
        session_id,
        content: MessageType::Response(ResponseType::ChatResponse(ChatResponse::MessageSent)),
    };

    let expected_fragments = NaiveAssembler::disassemble(&expected_source_message.stringify().into_bytes());

    let mut received_fragments = Vec::new();
    for _ in 0..expected_fragments.len() {
        let received = server_to_source_rx.recv().unwrap();
        match received.pack_type {
            PacketType::MsgFragment(fragment) => received_fragments.push(fragment),
            _ => panic!("Received unexpected packet {received:?}"),
        }
    }
    received_fragments.sort_by_key(|fragment| fragment.fragment_index);

    let received_message = NaiveAssembler::reassemble(&received_fragments);
    let received_message = String::from_utf8(received_message).unwrap();
    let received_message: Message = MessageUtilities::from_string(received_message).unwrap();

    assert_eq!(received_message, expected_source_message);
}

fn get_client_list(
    source: NodeId,
    destination: NodeId,
    session_id: u64,
    drones_to_server_tx: &Sender<Packet>,
    server_to_source_rx: &Receiver<Packet>,
    expected_message: Message,
    expected_routing_header: SourceRoutingHeader,
) {
    let content = MessageType::Request(
        RequestType::ChatRequest(
            ChatRequest::ClientList
        )
    );
    let request = Message {
        source,
        destination,
        session_id,
        content,
    };

    send_message_and_receive_acks(server_to_source_rx, drones_to_server_tx, source, destination, session_id, request);

    let expexted_packets = NaiveAssembler::disassemble(&expected_message.stringify().into_bytes());

    let mut received_fragments = Vec::new();
    for _ in 0..expexted_packets.len() {
        let received_packet = server_to_source_rx.recv().unwrap();
        assert_eq!(received_packet.session_id, session_id);
        assert_eq!(received_packet.routing_header, expected_routing_header);
        match received_packet.pack_type {
            PacketType::MsgFragment(fragment) => received_fragments.push(fragment),
            _ => panic!("Received unexpected packet type. {received_packet:?}"),
        }
    }

    received_fragments.sort_by_key(|fragment| fragment.fragment_index);
    let received_message = NaiveAssembler::reassemble(&received_fragments);
    let received_message = String::from_utf8(received_message).unwrap();
    let received_message: Message = MessageUtilities::from_string(received_message).unwrap();

    assert_eq!(received_message, expected_message);
}

fn register_node_id(source: NodeId, destination: NodeId, session_id: u64, drones_to_server_tx: &Sender<Packet>, server_to_source_rx: &Receiver<Packet>) {
    let content = MessageType::Request(
        RequestType::ChatRequest(
            ChatRequest::Register
        )
    );
    let request = Message {
        source,
        destination,
        session_id,
        content,
    };
    send_message_and_receive_acks(server_to_source_rx, drones_to_server_tx, source, destination, session_id, request);

}